/*
 * generated by Xtext
 */
package hr.fer.rasip.remes.profile;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ProfileRuntimeModule extends hr.fer.rasip.remes.profile.AbstractProfileRuntimeModule {

}
