/*
* generated by Xtext
*/
package hr.fer.rasip.remes.profile.ui.contentassist;

import hr.fer.rasip.remes.profile.ui.contentassist.AbstractProfileProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ProfileProposalProvider extends AbstractProfileProposalProvider {

}
