<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="gum"
    nsURI="http://www.rasip.fer.hr/gum/0.1.0/gum.ecore" nsPrefix="gum">
  <eSubpackages name="structure" nsURI="http://www.rasip.fer.hr/gum/0.1.0/structure.ecore"
      nsPrefix="structure">
    <eClassifiers xsi:type="ecore:EClass" name="Behaver" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="behaviour" eType="#//behaviour/Behaviour"
          eOpposite="#//behaviour/Behaviour/behavers"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Primitive" eSuperTypes="#//structure/Behaver #//structure/StructureElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="active" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Composite" eSuperTypes="#//structure/Behaver #//structure/StructureElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
          eType="#//structure/StructureElement" containment="true" eOpposite="#//structure/StructureElement/parent"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="connections" upperBound="-1"
          eType="#//structure/Connection" containment="true" eOpposite="#//structure/Connection/parent"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="active" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Port" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1"
          eType="#//structure/PortType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="group" lowerBound="1"
          eType="#//structure/PortGroup" eOpposite="#//structure/PortGroup/ports"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DataPort" eSuperTypes="#//structure/Port"/>
    <eClassifiers xsi:type="ecore:EClass" name="MessagePort" eSuperTypes="#//structure/Port"/>
    <eClassifiers xsi:type="ecore:EClass" name="TriggerPort" eSuperTypes="#//structure/Port"/>
    <eClassifiers xsi:type="ecore:EClass" name="Connection">
      <eStructuralFeatures xsi:type="ecore:EReference" name="connectFrom" lowerBound="1"
          eType="#//structure/Port"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="connectTo" lowerBound="1"
          eType="#//structure/Port"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
          eType="#//structure/Composite" eOpposite="#//structure/Composite/connections"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Connector" eSuperTypes="#//structure/StructureElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1"
          eType="#//structure/ConnectorType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PortGroup">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ports" upperBound="-1"
          eType="#//structure/Port" containment="true" eOpposite="#//structure/Port/group"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="interface" lowerBound="1"
          eType="#//structure/Interface" eOpposite="#//structure/Interface/inputPortGroups"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Interface" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="inputPortGroups" upperBound="-1"
          eType="#//structure/PortGroup" containment="true" eOpposite="#//structure/PortGroup/interface"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outputPortGroups" upperBound="-1"
          eType="#//structure/PortGroup" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StructureElement" abstract="true"
        eSuperTypes="#//structure/Interface">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//structure/Composite"
          eOpposite="#//structure/Composite/children"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="PortType">
      <eLiterals name="Trigger" literal="Trigger"/>
      <eLiterals name="Data" value="1" literal="Data"/>
      <eLiterals name="Message" value="2" literal="Message"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ConnectorType">
      <eLiterals name="ControlOr" literal="ControlOr"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="behaviour" nsURI="http://www.rasip.fer.hr/gum/0.1.0/behaviour.ecore"
      nsPrefix="behaviour">
    <eClassifiers xsi:type="ecore:EClass" name="Behaviour" eSuperTypes="#//behaviour/Context">
      <eStructuralFeatures xsi:type="ecore:EReference" name="behavers" upperBound="-1"
          eType="#//structure/Behaver" eOpposite="#//structure/Behaver/behaviour"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="modes" upperBound="-1"
          eType="#//behaviour/Mode" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="topModes" upperBound="-1"
          eType="#//behaviour/Mode"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Context" abstract="true">
      <eOperations name="getReadableVariables" upperBound="-1" eType="#//behaviour/Variable"/>
      <eOperations name="getWritableVariables" upperBound="-1" eType="#//behaviour/Variable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
          eType="#//behaviour/Variable" containment="true" eOpposite="#//behaviour/Variable/scope"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="resources" upperBound="-1"
          eType="#//behaviour/Resource" containment="true" eOpposite="#//behaviour/Resource/scope"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="constants" upperBound="-1"
          eType="#//behaviour/Constant" containment="true" eOpposite="#//behaviour/Constant/scope"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="renamings" upperBound="-1"
          eType="#//behaviour/Renaming" containment="true" eOpposite="#//behaviour/Renaming/context"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Mode" abstract="true" eSuperTypes="#//behaviour/Context">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="incomingEdges" upperBound="-1"
          eType="#//behaviour/Edge" eOpposite="#//behaviour/Edge/connectTo"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingEdges" upperBound="-1"
          eType="#//behaviour/Edge" containment="true" eOpposite="#//behaviour/Edge/connectFrom"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingBehaviour" lowerBound="1"
          eType="#//behaviour/Behaviour"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="invariant" eType="#//expressions/LogicalRoot"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CompositeMode" eSuperTypes="#//behaviour/Mode">
      <eStructuralFeatures xsi:type="ecore:EReference" name="modes" lowerBound="1"
          upperBound="-1" eType="#//behaviour/AtomicMode" containment="true" eOpposite="#//behaviour/AtomicMode/parent"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="initEdge" eType="#//behaviour/InitEdge"
          containment="true" eOpposite="#//behaviour/InitEdge/connectFrom"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AtomicMode" eSuperTypes="#//behaviour/Mode">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
          eType="#//behaviour/CompositeMode" eOpposite="#//behaviour/CompositeMode/modes"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Referable" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="#//behaviour/Referable">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1"
          eType="#//behaviour/PrimitiveTypes"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="scope" lowerBound="1"
          eType="#//behaviour/Context" eOpposite="#//behaviour/Context/variables"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="readable" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="writable" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="-1"
          eType="#//core/Data"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Resource" eSuperTypes="#//behaviour/Referable">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1"
          eType="#//behaviour/ResourceTypes"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="scope" lowerBound="1"
          eType="#//behaviour/Context" eOpposite="#//behaviour/Context/resources"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//expressions/ResourceRoot"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="resolved" eType="#//profile/Resource"
          eOpposite="#//profile/Resource/references"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Constant" eSuperTypes="#//behaviour/Referable">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1"
          eType="#//behaviour/PrimitiveTypes"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="scope" lowerBound="1"
          eType="#//behaviour/Context" eOpposite="#//behaviour/Context/constants"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//core/Data"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="resolved" eType="#//profile/ConstantValue"
          eOpposite="#//profile/ConstantValue/definition"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Edge">
      <eStructuralFeatures xsi:type="ecore:EReference" name="connectFrom" lowerBound="1"
          eType="#//behaviour/Mode" eOpposite="#//behaviour/Mode/outgoingEdges"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="connectTo" lowerBound="1"
          eType="#//behaviour/Mode" eOpposite="#//behaviour/Mode/incomingEdges"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="actionGuard" eType="#//expressions/LogicalRoot"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="actionBody" eType="#//expressions/ActionRoot"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InitEdge">
      <eStructuralFeatures xsi:type="ecore:EReference" name="connectFrom" lowerBound="1"
          eType="#//behaviour/CompositeMode" eOpposite="#//behaviour/CompositeMode/initEdge"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="connectTo" lowerBound="1"
          eType="#//behaviour/Mode"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="initialization" eType="#//expressions/ActionRoot"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Renaming">
      <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1"
          eType="#//behaviour/Referable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="#//behaviour/Referable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="context" lowerBound="1"
          eType="#//behaviour/Context" eOpposite="#//behaviour/Context/renamings"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="PrimitiveTypes">
      <eLiterals name="integer"/>
      <eLiterals name="boolean" value="1"/>
      <eLiterals name="natural" value="2"/>
      <eLiterals name="clock" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ResourceTypes">
      <eLiterals name="cpu"/>
      <eLiterals name="memory" value="1"/>
      <eLiterals name="bandwidth" value="2"/>
      <eLiterals name="power" value="3"/>
      <eLiterals name="port" value="4"/>
      <eLiterals name="EEnumLiteral0" value="5"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="core" nsURI="http://www.rasip.fer.hr/gum/0.1.0/core.ecore" nsPrefix="core">
    <eClassifiers xsi:type="ecore:EClass" name="Data" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="ClockType" eSuperTypes="#//core/Data"/>
    <eClassifiers xsi:type="ecore:EClass" name="IntegerType" eSuperTypes="#//core/Data"/>
    <eClassifiers xsi:type="ecore:EClass" name="BooleanType" eSuperTypes="#//core/Data"/>
    <eClassifiers xsi:type="ecore:EClass" name="NaturalType" eSuperTypes="#//core/Data"/>
    <eClassifiers xsi:type="ecore:EClass" name="FloatType" eSuperTypes="#//core/Data"/>
  </eSubpackages>
  <eSubpackages name="expressions" nsURI="http://www.rasip.fer.hr/gum/0.1.0/expressions.ecore"
      nsPrefix="expressions.ast">
    <eClassifiers xsi:type="ecore:EClass" name="AbstractRoot" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="referencedVariables"
          upperBound="-1" eType="#//expressions/VariableReference"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ActionRoot" eSuperTypes="#//expressions/AbstractRoot">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" lowerBound="1"
          upperBound="-1" eType="#//expressions/Expression" containment="true" resolveProxies="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LogicalRoot" eSuperTypes="#//expressions/AbstractRoot">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
          eType="#//expressions/Expression" containment="true" resolveProxies="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ResourceRoot" eSuperTypes="#//expressions/AbstractRoot">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
          eType="#//expressions/Expression" containment="true" resolveProxies="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="TernaryExpression" eSuperTypes="#//expressions/Expression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1"
          eType="#//expressions/TernaryOperation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="param1" lowerBound="1"
          eType="#//expressions/Expression" containment="true" resolveProxies="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="param2" lowerBound="1"
          eType="#//expressions/Expression" containment="true" resolveProxies="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="param3" lowerBound="1"
          eType="#//expressions/Expression" containment="true" resolveProxies="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BinaryExpression" eSuperTypes="#//expressions/Expression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1"
          eType="#//expressions/BinaryOperation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="param1" lowerBound="1"
          eType="#//expressions/Expression" containment="true" resolveProxies="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="param2" lowerBound="1"
          eType="#//expressions/Expression" containment="true" resolveProxies="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UnaryExpression" eSuperTypes="#//expressions/Expression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1"
          eType="#//expressions/UnaryOperation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="param1" lowerBound="1"
          eType="#//expressions/Expression" containment="true" resolveProxies="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VariableReference" eSuperTypes="#//expressions/Expression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="arrayIndex" eType="#//expressions/Expression"
          containment="true" resolveProxies="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="resolved" lowerBound="1"
          eType="#//behaviour/Referable"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Constant" eSuperTypes="#//expressions/Expression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Literal" eSuperTypes="#//expressions/Expression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="TernaryOperation">
      <eLiterals name="QUESTION"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="BinaryOperation">
      <eLiterals name="ADD"/>
      <eLiterals name="SUB" value="1"/>
      <eLiterals name="MUL" value="2"/>
      <eLiterals name="DIV" value="3"/>
      <eLiterals name="MOD" value="4" literal="MOD"/>
      <eLiterals name="LT" value="5"/>
      <eLiterals name="LE" value="6"/>
      <eLiterals name="EQ" value="7"/>
      <eLiterals name="GE" value="8"/>
      <eLiterals name="GT" value="9"/>
      <eLiterals name="NE" value="10"/>
      <eLiterals name="AND" value="11"/>
      <eLiterals name="OR" value="12" literal="OR"/>
      <eLiterals name="ASSIGN" value="13"/>
      <eLiterals name="ASSIGN_ADD" value="14"/>
      <eLiterals name="ASSIGN_SUB" value="15"/>
      <eLiterals name="ASSIGN_MUL" value="16"/>
      <eLiterals name="ASSIGN_DIV" value="17"/>
      <eLiterals name="ASSIGN_MOD" value="18"/>
      <eLiterals name="DIFF" value="19"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="UnaryOperation">
      <eLiterals name="NOT"/>
      <eLiterals name="PLUS" value="1"/>
      <eLiterals name="MINUS" value="2"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="mapping" nsURI="http://www.rasip.fer.hr/gum/0.1.0/mapping.ecore"
      nsPrefix="mapping">
    <eClassifiers xsi:type="ecore:EClass" name="MappingModel">
      <eStructuralFeatures xsi:type="ecore:EReference" name="mappings" upperBound="-1"
          eType="#//mapping/Mapping" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Mapping">
      <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
          eType="#//behaviour/Referable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="port" lowerBound="1"
          eType="#//structure/Port"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="simulator" nsURI="http://www.rasip.fer.hr/gum/0.1.0/simulator.ecore"
      nsPrefix="simulator">
    <eClassifiers xsi:type="ecore:EClass" name="SimulatorConfiguration">
      <eStructuralFeatures xsi:type="ecore:EReference" name="sensors" upperBound="-1"
          eType="#//simulator/Sensor" containment="true" eOpposite="#//simulator/Sensor/configuration"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="system" eType="#//structure/StructureElement"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="profile" eType="#//profile/PlatformProfile"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Sensor">
      <eStructuralFeatures xsi:type="ecore:EReference" name="configuration" lowerBound="1"
          eType="#//simulator/SimulatorConfiguration" eOpposite="#//simulator/SimulatorConfiguration/sensors"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
          eType="#//behaviour/Referable"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="trigger" lowerBound="1"
          eType="#//simulator/SensorTrigger"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="SensorTrigger">
      <eLiterals name="ValueChange" literal="ValueChange"/>
      <eLiterals name="BehaviourExit" value="1"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="profile" nsURI="http://www.rasip.fer.hr/gum/0.1.0/profile.ecore"
      nsPrefix="profile">
    <eClassifiers xsi:type="ecore:EClass" name="PlatformProfile">
      <eStructuralFeatures xsi:type="ecore:EReference" name="resources" upperBound="-1"
          eType="#//profile/Resource" containment="true" eOpposite="#//profile/Resource/platform"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="constantValues" upperBound="-1"
          eType="#//profile/ConstantValue" containment="true" eOpposite="#//profile/ConstantValue/platform"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
          eType="#//profile/Constraint" containment="true" eOpposite="#//profile/Constraint/platform"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Resource" eSuperTypes="#//behaviour/Referable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="references" upperBound="-1"
          eType="#//behaviour/Resource" eOpposite="#//behaviour/Resource/resolved"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="platform" lowerBound="1"
          eType="#//profile/PlatformProfile" eOpposite="#//profile/PlatformProfile/resources"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1"
          eType="#//behaviour/ResourceTypes"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConstantValue">
      <eStructuralFeatures xsi:type="ecore:EReference" name="platform" lowerBound="1"
          eType="#//profile/PlatformProfile" eOpposite="#//profile/PlatformProfile/constantValues"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="definition" eType="#//behaviour/Constant"
          eOpposite="#//behaviour/Constant/resolved"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1"
          eType="#//core/Data" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Constraint">
      <eStructuralFeatures xsi:type="ecore:EReference" name="references" lowerBound="1"
          eType="#//behaviour/Referable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="platform" lowerBound="1"
          eType="#//profile/PlatformProfile" eOpposite="#//profile/PlatformProfile/constraints"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ConstraintType"/>
    <eClassifiers xsi:type="ecore:EEnum" name="ConstraintOperation"/>
  </eSubpackages>
</ecore:EPackage>
