/*
 * generated by Xtext
 */
package hr.fer.rasip.remes.profile.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ProfileUiModule extends hr.fer.rasip.remes.profile.ui.AbstractProfileUiModule {
	public ProfileUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
