/*
* generated by Xtext
*/
package hr.fer.rasip.remes.profile.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ProfileAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("hr/fer/rasip/remes/profile/parser/antlr/internal/InternalProfile.tokens");
	}
}
