/*
* generated by Xtext
*/
package hr.fer.rasip.remes.profile.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import hr.fer.rasip.remes.profile.services.ProfileGrammarAccess;

public class ProfileParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ProfileGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected hr.fer.rasip.remes.profile.parser.antlr.internal.InternalProfileParser createParser(XtextTokenStream stream) {
		return new hr.fer.rasip.remes.profile.parser.antlr.internal.InternalProfileParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "PlatformProfile";
	}
	
	public ProfileGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ProfileGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
