/*
* generated by Xtext
*/
package hr.fer.rasip.remes.profile.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import hr.fer.rasip.remes.profile.services.ProfileGrammarAccess;

public class ProfileParser extends AbstractContentAssistParser {
	
	@Inject
	private ProfileGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected hr.fer.rasip.remes.profile.ui.contentassist.antlr.internal.InternalProfileParser createParser() {
		hr.fer.rasip.remes.profile.ui.contentassist.antlr.internal.InternalProfileParser result = new hr.fer.rasip.remes.profile.ui.contentassist.antlr.internal.InternalProfileParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getResourceTypeAccess().getAlternatives(), "rule__ResourceType__Alternatives");
					put(grammarAccess.getConstraintTypeAccess().getAlternatives(), "rule__ConstraintType__Alternatives");
					put(grammarAccess.getConstraintOperationAccess().getAlternatives(), "rule__ConstraintOperation__Alternatives");
					put(grammarAccess.getPlatformProfileAccess().getGroup(), "rule__PlatformProfile__Group__0");
					put(grammarAccess.getPlatformProfileAccess().getGroup_4(), "rule__PlatformProfile__Group_4__0");
					put(grammarAccess.getPlatformProfileAccess().getGroup_4_3(), "rule__PlatformProfile__Group_4_3__0");
					put(grammarAccess.getPlatformProfileAccess().getGroup_5(), "rule__PlatformProfile__Group_5__0");
					put(grammarAccess.getPlatformProfileAccess().getGroup_5_3(), "rule__PlatformProfile__Group_5_3__0");
					put(grammarAccess.getResourceAccess().getGroup(), "rule__Resource__Group__0");
					put(grammarAccess.getResourceAccess().getGroup_3(), "rule__Resource__Group_3__0");
					put(grammarAccess.getConstraintAccess().getGroup(), "rule__Constraint__Group__0");
					put(grammarAccess.getPlatformProfileAccess().getNameAssignment_2(), "rule__PlatformProfile__NameAssignment_2");
					put(grammarAccess.getPlatformProfileAccess().getResourcesAssignment_4_2(), "rule__PlatformProfile__ResourcesAssignment_4_2");
					put(grammarAccess.getPlatformProfileAccess().getResourcesAssignment_4_3_1(), "rule__PlatformProfile__ResourcesAssignment_4_3_1");
					put(grammarAccess.getPlatformProfileAccess().getConstraintsAssignment_5_2(), "rule__PlatformProfile__ConstraintsAssignment_5_2");
					put(grammarAccess.getPlatformProfileAccess().getConstraintsAssignment_5_3_1(), "rule__PlatformProfile__ConstraintsAssignment_5_3_1");
					put(grammarAccess.getResourceAccess().getNameAssignment_0(), "rule__Resource__NameAssignment_0");
					put(grammarAccess.getResourceAccess().getTypeAssignment_2(), "rule__Resource__TypeAssignment_2");
					put(grammarAccess.getResourceAccess().getWeightAssignment_3_1(), "rule__Resource__WeightAssignment_3_1");
					put(grammarAccess.getConstraintAccess().getTypeAssignment_0(), "rule__Constraint__TypeAssignment_0");
					put(grammarAccess.getConstraintAccess().getReferencesAssignment_2(), "rule__Constraint__ReferencesAssignment_2");
					put(grammarAccess.getConstraintAccess().getIsDerivationAssignment_3(), "rule__Constraint__IsDerivationAssignment_3");
					put(grammarAccess.getConstraintAccess().getOperationAssignment_5(), "rule__Constraint__OperationAssignment_5");
					put(grammarAccess.getConstraintAccess().getBoundAssignment_6(), "rule__Constraint__BoundAssignment_6");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			hr.fer.rasip.remes.profile.ui.contentassist.antlr.internal.InternalProfileParser typedParser = (hr.fer.rasip.remes.profile.ui.contentassist.antlr.internal.InternalProfileParser) parser;
			typedParser.entryRulePlatformProfile();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public ProfileGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ProfileGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
