/*
* generated by Xtext
*/
package hr.fer.rasip.remes.profile.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class ProfileOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
